{"code":8000,"codeName":"AtlasError","connectionGeneration":0,"level":"error","message":"MongoDB connection error: bad auth : authentication failed","ok":0,"service":"PvP-Planner-Bot","stack":"MongoServerError: bad auth : authentication failed\n    at Connection.onMessage (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\connection.js:231:30)\n    at MessageStream.<anonymous> (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\connection.js:61:60)\n    at MessageStream.emit (node:events:518:28)\n    at processIncomingData (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:125:16)\n    at MessageStream._write (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:572:12)\n    at _write (node:internal/streams/writable:501:10)\n    at Writable.write (node:internal/streams/writable:510:10)\n    at TLSSocket.ondata (node:internal/streams/readable:1009:22)\n    at TLSSocket.emit (node:events:518:28)","timestamp":"2024-11-01 10:15:15"}
{"code":8000,"codeName":"AtlasError","connectionGeneration":0,"level":"error","message":"MongoDB connection error: bad auth : authentication failed","ok":0,"service":"PvP-Planner-Bot","stack":"MongoServerError: bad auth : authentication failed\n    at Connection.onMessage (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\connection.js:231:30)\n    at MessageStream.<anonymous> (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\connection.js:61:60)\n    at MessageStream.emit (node:events:518:28)\n    at processIncomingData (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:125:16)\n    at MessageStream._write (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\mongodb\\lib\\cmap\\message_stream.js:33:9)\n    at writeOrBuffer (node:internal/streams/writable:572:12)\n    at _write (node:internal/streams/writable:501:10)\n    at Writable.write (node:internal/streams/writable:510:10)\n    at TLSSocket.ondata (node:internal/streams/readable:1009:22)\n    at TLSSocket.emit (node:events:518:28)","timestamp":"2024-11-01 10:20:48"}
{"code":10062,"level":"error","message":"Error executing viewcalendar command: Unknown interaction","method":"POST","rawError":{"code":10062,"message":"Unknown interaction"},"requestBody":{"json":{"data":{},"type":5}},"service":"PvP-Planner-Bot","stack":"DiscordAPIError[10062]: Unknown interaction\n    at handleErrors (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\@discordjs\\rest\\dist\\index.js:727:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async BurstHandler.runRequest (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\@discordjs\\rest\\dist\\index.js:831:23)\n    at async _REST.request (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\@discordjs\\rest\\dist\\index.js:1272:22)\n    at async ChatInputCommandInteraction.deferReply (C:\\Users\\Jacin\\PvP-Planner\\node_modules\\discord.js\\src\\structures\\interfaces\\InteractionResponses.js:72:5)\n    at async Object.execute (C:\\Users\\Jacin\\PvP-Planner\\commands\\viewcalendar.js:14:7)\n    at async Object.execute (C:\\Users\\Jacin\\PvP-Planner\\events\\interactionCreate.js:12:9)","status":404,"timestamp":"2024-11-01 16:15:51","url":"https://discord.com/api/v10/interactions/1302003192392843364/aW50ZXJhY3Rpb246MTMwMjAwMzE5MjM5Mjg0MzM2NDp6V3lNNTdhM0lGQ3JiVUUzSnQwcWRqbUVMeHZPU0lTMzdJRFIwcDExOWtqRWlkNWl5Ymc2SDBNRDRPSlNMUXJwakp3TldncHoxZmluaXlVeGs5T3NsT3hNMkVIczFmYmdVQWE1UWRwRDRZNEFOUmRGNHBVWEV6ZEt5UTVpRXFwRg/callback"}
